### ISSUE TITLE
Navigate through search results using Alt+Up/Down

### ISSUE THREAD

**Issue by ManuelSchneid3r** [zealdocs/zeal#1007]
This is common practice for "tabbing" though a vertical list. This would be awesome since I start a zeal seach using albert from keyboard. Initially the matchlist is focussed. When I click a result it loses focus and then I have to use the mouse to select another result.

**Comment by trollixx** [comment]
Just to clarify, the idea here is that <kbd>Alt+Up/Down</kbd> should always move selection up/down in the search results?

In this scenario another question comes up - when should we trigger loading of the new content? Since focus is not in the list widget, <kbd>Enter</kbd> wouldn't work. Perhaps, rely on <kbd>Alt+Enter</kbd> then...

**Comment by ManuelSchneid3r** [comment]
Yes always move and directly load content. Thats a convenient way to browse the results without the need to touch the mouse.

**Comment by trollixx** [comment]
This should play nicely with #749, since I do want to give an option to decide when a page should be loaded.

**Comment by trollixx** [comment]
Finally got to implementing this, please test!
