### ISSUE TITLE
Support MITM certificates on Windows

### ISSUE THREAD

**Issue by michaeljmcd** [zealdocs/zeal#1022]
I am attempting to use Zeal (version 0.6.1 of the Windows Portable install, 0.6.0 on Ubuntu/WSL) behind a corporate proxy with a self-signed certificate. I am unable to download any docsets, receiving the "SSL handshake failed" error message each time. I presume this is due to a need to import the proxy certificates, but I am not sure how to do this.

The certificates are already imported into the system store, as evidenced by other applications working.

How do I trust the additional certificates for the corporate proxyu so that I can download docsets?

**Comment by trollixx** [comment]
After some research it appears that on Windows Qt/OpenSSL do not load certificates from the system's certificate store. I also was unable to find an easy way to add a trusted certificate to Zeal without recompiling it.

We need to address this, since MITM setups are quite common in the corporate world, but I don't think I will work on this until the new app backend is out.

**Comment by trollixx** [comment]
Combination of #1367 and #1521 should address this.
