### ISSUE TITLE
Provide an AppImage

### ISSUE THREAD

**Issue by azubieta** [zealdocs/zeal#1194]
AppImage is a great format for making portable applications on GNU/Linux. It would be great to have one for zeal.

If you like I can make a recipe for you :)

**Comment by trollixx** [comment]
There was a long discussion about this in https://github.com/zealdocs/zeal-packaging/issues/34, @probonopd posted his build recipes as well. I don't mind, but since I don't use either Ubuntu, AppImage or Travis I have never gotten to packaging.

Also personally I am not a big fan of AppImage because it targets the oldest supported Ubuntu LTS, while I only care about the most the recent LTS release, and idea of pulling third-party PPA for Qt doesn't appeal to me.

I think the best scenario would be if someone else maintained the packages, similarly to what every Linux distro does.

**Comment by azubieta** [comment]
>  I don't use either Ubuntu, AppImage or Travis

You can also use Centos and any other CI system.

> it targets the oldest supported Ubuntu LTS,

There are new ways of producing AppImages now, there is no need for targeting an old system.

Will send a PR next week for you to see :)

**Comment by trollixx** [comment]
Will keep this open until all the tasks below are complete.

A new GitHub Action is now building AppImage for every commit to master, and uploads an associated artifact. Uploading of `.zsync` files is currently disabled, because I am not sure how to make updates work for CI builds, although offering some kind of "dev channel" would be nice.

There are still a few quirks to figure out:

- [ ] Automatically picking up the correct version (now `0.6.1` is hard-coded).
- [ ] Sign the produced AppImage
- [ ] Upload artifacts to releases, when a new release is created.
- [ ] _Bonus:_ Refactor the action into a separate repository, and use a prebuilt Docker container.

**Comment by azubieta** [comment]
On the `Automatically picking up the correct version (now 0.6.1 is hard-coded)` point. You can use environment variables in the script. So if you have a way of guessing the version from the code then you can export it to the environment before calling appimage-builder.

Check https://appimage-builder.readthedocs.io/en/latest/recipe/version_1.html#environment-variables

**Comment by probonopd** [comment]
> Uploading of .zsync files is currently disabled, because I am not sure how to make updates work for CI builds, although offering some kind of "dev channel" would be nice.

For the combination of Travis CI and GitHub Releases we have this (as the default actually) but I have never looked into GitHub Actions. @azubieta is this something you might be able to look into?

**Comment by lebensterben** [comment]
@trollixx 
To get the version string from cmake, we may add the following shell commands to
`pkg/appimage/appimage-amd64.yml`

```bash
grep 'CMAKE_PROJECT_VERSION:STATIC' ../../CMakeCache.txt | cut -d'=' -f2
```

wwhere `CMakeCache.txt` could be generated by

```bash
cmake -L ../../CMakeList.txt
```

if it doesn't exist.

**Comment by trollixx** [comment]
@lebensterben thank you, yes, it should be read from CMake.

Still need to decide on versioning for these releases. I am inclined to use `major.minor.(patch+1)-dev.N.SHA` to be more or less in compliance with the semver.

**Comment by probonopd** [comment]
Hi all, what is the status on the AppImage effort? Is there something holding it back from appearing on https://zealdocs.org/download.html?

**Comment by trollixx** [comment]
@probonopd I'll release it once 0.7.0 is ready. Still need to address a few regressions from the migration to Qt WebEngine.

**Comment by David-Else** [comment]
@trollixx I see https://github.com/zealdocs/zeal/pull/1276 . Is there anywhere to download this AppImage yet? The long-awaited new version of Zeal feels so near! :)

**Comment by misaka00251** [comment]
Hello, any update on this?

**Comment by oclero** [comment]
Hi! What's the status of this issue?

**Comment by ShrirajHegde** [comment]
here for the appimage :eyes:

**Comment by trollixx** [comment]
All recent [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) have AppImage attached as an artifact.

**Comment by David-Else** [comment]
@trollixx The appimage seems to be working well on Centos/Rocky 8.4 :) Hope there is an official release asap, great work!

**Comment by ShrirajHegde** [comment]
> @trollixx The appimage seems to be working well on Centos/Rocky 8.4 :) Hope there is an official release asap, great work!

where's the link

**Comment by David-Else** [comment]
@ShrirajHegde https://github.com/zealdocs/zeal/suites/3208003709/artifacts/74197191 , but I think it will expire, so grab it now.

**Comment by ShrirajHegde** [comment]
Thanks, found it
