### ISSUE TITLE
Doesn't navigate to markers that contain underscores

### ISSUE THREAD

**Issue by 3flex** [zealdocs/zeal#121]
Not sure if 'markers' is the right word, but if there's a bookmark on the left with an underscore in it Zeal won't scroll down to that position when clicked (it opens the page being viewed, but doesn't scroll down to the position where the item is described).

To replicate, download the Nginx docset, expand "Directives", and try opening "aio", "alias" and "chunked_transfer_encoding". These are all on the same documentation page. aio and alias scroll to the correct position, but chunked_transfer_encoding doesn't.

**Comment by trollixx** [comment]
The problem occurs because internally QUrl decodes percent encoded symbols by default, and then Webkit cannot match decoded anchors to their encoded equivalents. That is not an issue with Firefox, example. We could force another behaviour of course, but it just doesn't seem normal to have encoded URLs within pages.

@Kapeli, is there a specific reason why anchor name stays percent encoded for nginx docset?

**Comment by Kapeli** [comment]
Dash uses those anchors to figure out what the name for the entries & sections is while building the in-page table of contents. Making them percent encoded saves me from trouble with symbols/emojis and so on.
