### ISSUE TITLE
Mouse Side Button cannot function properly for going forward/back navigation.

### ISSUE THREAD

**Issue by Bili-TianX** [zealdocs/zeal#1564]
When the side buttons are pressed, the page will go forward/back twice

**Comment by jorio** [comment]
I'm also seeing this. Navigation goes back on button down (OK) and also on button up (unexpected).

**Comment by gaotongsh** [comment]
I have the same issue.

**Comment by cragwen** [comment]
It seems like not need to call back() or forward() function in handleMousePressEvent of webview.cpp. I try to comment out these lines and compile. It works fine for me.

**Comment by gaotongsh** [comment]
> It seems like not need to call back() or forward() function in handleMousePressEvent of webview.cpp. I try to comment out these lines and compile. It works fine for me.

Thanks. Can you make a PR or can the developers take a look at the fix? @trollixx

**Comment by crimsonskylark** [comment]
I spent some time debugging this today, although I wasn't able to figure out the root cause it doesn't seem to be a problem with Zeal proper, but rather some behavioural change in WebEngine. The `back()` function is only called once, which leads me to believe whatever is changing the page a second time is doing internally from the framework. 

I'm not at all familiar with Qt, but figured I'd share my finding in the hopes it might help solve the problem.

**Comment by trollixx** [comment]
I updated the logic to use button release event and also check that pointer is still inside web view. This should address this issue.
