### ISSUE TITLE
Search keyword discoverability

### ISSUE THREAD

**Issue by Pescheee** [zealdocs/zeal#1617]
ive been using Zeal for quite some time now and now i thought i wanted to add the commands for bash too, but my problem is they are hard to find because some words get shown higher up even tho you wrote the complete name of the bash command, it would be awesome if you could exclude languages in the search bar so you just get showed what you want

**Comment by novaTopFlex** [comment]
Unfortunately, I believe that this is a common problem for users of the Zeal documentation browser, particularly those who have installed Dash Docsets for various programming languages. I have installed a double-digit number of programming languages and very rarely use the search bar, but when I do, my searches are of varied success. There may also be pages of guides and sections of very similar to nearly identical names.
***
By excluding languages in the search bar, more advanced developers, such as developers and users of C, C++, and the `bash` shell, may become somewhat more confused than they (normally) would otherwise.

**Comment by novaTopFlex** [comment]
I have just removed my Zeal v0.6.1 installation and compiled my new installation of Zeal v0.7.0-dev from source, and the latter is capable of searching more quickly than the former.

**Comment by trollixx** [comment]
All docsets have search keywords (prefixes). Discoverability was definitely an issue. Since https://github.com/zealdocs/zeal/commit/07a357cab00ae6b9cd999eed27ce00be938ee9fb it's now possible to view all keywords in the docset manager:

![image](https://github.com/zealdocs/zeal/assets/714940/41a00e13-4652-4544-b465-1b282bf44ee8)
