### ISSUE TITLE
Font rendering problems with Qt WebKit

### ISSUE THREAD

**Issue by ataafarin** [zealdocs/zeal#359]
Hi,
I have problem with the font of zeal.as you can see in below picture, the texts(specially in Overview and Example Section) are not showing well.
![zeal](https://cloud.githubusercontent.com/assets/2671352/8403067/8eb14902-1e56-11e5-85fb-06615bd69e84.png)

**Comment by SammaySarkar** [comment]
**File > Options > Appearance tab > Minimum font size**: set a value that works. In my case `13` was good enough.

**Comment by arashmobileboy** [comment]
As you can see the problem exist with the font size:14
![zeal](https://cloud.githubusercontent.com/assets/2671352/8408913/1dab74fc-1e89-11e5-9fb7-1579525bf78f.png)

**Comment by SammaySarkar** [comment]
make a few more increments?

**Comment by arashmobileboy** [comment]
that's better now.Thanks

**Comment by trollixx** [comment]
Hm, it really a font rendering issue. I bet something wrong in Qt WebKit which is not officially supported any longer. Zeal needs a new web view engine, but there's no drop-in replacement we could use.

I'll leave this open to run some tests once I have access to Windows machine, but most likely there's nothing I could do for now :(

**Comment by SammaySarkar** [comment]
maybe you could meanwhile add zoom in/out shortcuts <kbd>CTRL</kbd><kbd>+</kbd>,<kbd>CTRL</kbd><kbd>-</kbd>

**Comment by artursapek** [comment]
Agreed with @smsrkr - a zoom function would be very welcome. Ideally it would default to OS scale settings, because I think the webkit view is rendering at a 100% scale despite OS settings (Ubuntu 16.04 here). For example I am using Ubuntu at 150% UI scale because I have a high DPI screen, but in zeal the docs are rendered disproportionately smaller than the rest of the UI.

Min font size kind of addresses it, but then you lose the benefit of larger headings etc.

![image](https://cloud.githubusercontent.com/assets/897596/20650604/73f34b88-b4a0-11e6-9313-9b125269fe10.png)

**Comment by damianpeterson** [comment]
![zeal](https://cloud.githubusercontent.com/assets/599724/25991188/8fd9c802-3756-11e7-8860-7af164c9e253.png)
Just adding my own screenshot at 2x scaling on a 3200x1800px laptop in Ubuntu 17.04

**Comment by trollixx** [comment]
[CI builds](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view) for Windows are now based on the new Qt WebKit (qtwebkit-ng), which should resolve the most of the issues with rendering. Please give it a try.

Linux users need to install qtwebkit-ng themselves, although some distros do provide binaries.

**Comment by trollixx** [comment]
The majority of font rendering issues can be fixed by upgrading the the new Qt WebKit. If an issue persists even with qtwebkit-ng (like #658), please create a new ticket.
