### ISSUE TITLE
docset search works different than Dash

### ISSUE THREAD

**Issue by darrennoble** [zealdocs/zeal#383]
I just installed Zeal and tries using the IntelliJ Idea plugin with it on both a python project and a java project and it doesn't work well.  The plugin generates search strings with a bunch of docsets separated by commas, then a colon and then the search word.  They get passed into Zeal just fine, but the problem is that Zeal doesn't support the same docset names as Dash and so the results show nothing.

I created a ticket with the IntelliJ Idea plugin and the developer there said that Zeal would need to add support for the same keywords that Dash uses (apparently in the Dash code somewhere it maintains a mapping of search prefixes to docsets).

Here is the ticket I logged with the plugin:  https://github.com/gdelmas/IntelliJDashPlugin/issues/44

And here is a ticket he referenced where he discusses this with the Dash developer: https://github.com/gdelmas/IntelliJDashPlugin/issues/23#issuecomment-45056264

**Comment by darrennoble** [comment]
Here are the 2 examples that are causing me issues:

To search for a Java 8 Map in Zeal I need the query:

```
java se8:Map
```

The same search in Dash is:

```
java8:Map
```

To search for datetime in python 2 in Zeal:

```
python 2:datetime
```

The same search in Dash (no space):

```
python2:datetime
```

**Comment by Kapeli** [comment]
> apparently in the Dash code somewhere it maintains a mapping of search prefixes to docsets

This is not correct. The `dash-plugin://` URL in Dash works with a list of keywords, not docset names.

Plugin keywords are used to find docsets within Dash by comparing the plugin-sent keyword to the following:

1. `DocSetPlatformFamily` (Info.plist)
2. `DashDocSetPluginKeyword` (Info.plist)
3. `DashDocSetKeyword` (Info.plist)
4. `DashDocSetFamily` (Info.plist)
5. The custom-keyword for the docset (Dash allows users to set any keywords they want for docsets)

If any of those match, the docset is enabled and searched. The docset name is not used at all.

In https://github.com/gdelmas/IntelliJDashPlugin/issues/23 @gdelmas chose to take `dash-plugin://` one step further by targeting specific docset versions using the default custom-keyword only Java and Python have (the default custom keywords for Java and Python have the version number in them - e.g. `java8` or `python3`).

However, the keywords are sent like this: `java8,java,javafx,grails,groovy,playjava,spring,cvj,processing,javadoc`

Even if Zeal doesn't support the custom-keyword `java8`, the keywords sent above should still correctly match all the Java docsets using the `java` keyword that is second in the list.

**Comment by darrennoble** [comment]
On my machine the Java keyword doesn't work.  Using "java se8" is the only way I've found to search inside Java only.  The Python keyword doesn't work either, but "Python 2" and "Python 3" both work.

**Comment by gdelmas** [comment]
this mean there is a custom default keyword hardcoded(?) into dash wich is `java8`, unless the user changes it. but this is not the root of the problem.

zeal does only use one keyword per docset (see [source](https://github.com/zealdocs/zeal/blob/f62a95b47d83762fb3136bfabaf5b61607f45aff/src/registry/docset.cpp#L81)). it does not use one of the Info.plist keys specified by @Kapeli. it uses [`CFBundleName`](https://github.com/zealdocs/zeal/blob/f62a95b47d83762fb3136bfabaf5b61607f45aff/src/registry/docsetinfo.cpp#L49-50) as keyword.

it would be ideal for zeal to support multiple keywords. if this is not feasible it should at least not use `CFBundleName`. i assume the keyword should be picked from the first field, described by @kapeli, that is not empty.

**Comment by Kapeli** [comment]
Please note that there's a difference between user-set keywords in Dash and the keywords `dash-plugin` matches against. While `dash-plugin` does take into account user-set keywords, it doesn't care too much about them (and the plugins shouldn't either).

> this mean there is a custom default keyword hardcoded(?) into dash wich is java8, unless the user changes it

Correct. The default user-set keyword for docsets is the `DocSetPlatformFamily`. Java and Python are special because they have their major version added and they have keywords like `java8` or `python3`. Again, this doesn't really matter as it **does not affect Zeal at all**. `dash-plugin` implementations should not even care about user-set keywords (on the editor plugin side). IntelliJDashPlugin cares because it was @gdelmas's choice, but it still doesn't affect Zeal at all because IntelliJDashPlugin still sends `java` as the second keyword in the list which should match properly.

> it would be ideal for zeal to support multiple keywords. if this is not feasible it should at least not use CFBundleName

Doing this just for `dash-plugin` would be ok.

> i assume the keyword should be picked from the first field, described by @kapeli, that is not empty.

No, this is wrong. The entire list of desired keywords `dash-plugin` sends is checked with each docset with the values in the list I gave above and if **any** of those match, then the docset is enabled.

**Comment by trollixx** [comment]
Unfortunately, in addition to missing some keyword-keyword related features, in 0.1.1 I accidentally made a change that forces exact prefix matching (see #333). That problem has been fixed, but not yet released.

A support for user keywords is something I plan to implement for the future 0.2 release (#167).

I'll add reading of all keyword elements from `Info.plist` for 0.1.2 then.

**Comment by trollixx** [comment]
@Kapeli,

1. According to [this](https://kapeli.com/docsets#tableofcontents), `DashDocSetFamily` should be set to `dashtoc` to enable TOC support. Why do you use it also for matching keywords?

2. Is `DocSetPlatformFamily` required for all docsets? If it's not available what is Dash using for tab completion in the search field? I imagine a scenario when one types `actionscr` and hits tab, and ActionScript docset has no `DocSetPlatformFamily` parameter.

3. Is there a list of all possible parameters in `Info.plist`? That would be extremely helpful.

Thanks!

**Comment by Kapeli** [comment]
> According to this, DashDocSetFamily should be set to dashtoc to enable TOC support. Why do you use it also as a keyword?

Because it can also contain other values which make sense to be matched by `dash-plugin`. For example, all docsets generated using [javadocset](http://github.com/Kapeli/javadocset) have their `DashDocSetFamily` set to `java`, so if `dash-plugin://` sends `java` in its list, all the docsets generated using javadocset are enabled.

> Is DocSetPlatformFamily required for all docsets? If it's not available what is Dash using for tab completion in the search field? I imagine a scenario when one types actionscr and hits tab, and ActionScript docset has no DocSetPlatformFamily parameter.

It's not required, but most docsets have it. If they don't have it, Dash uses `unknown` as the initial keyword.

> Is there a list of all possible parameters in Info.plist? That would be extremely helpful

Docsets can have a lot of parameters in Info.plist, especially the ones made by `appledoc` or `doxygen` and so on. These are the parameters Dash currently cares about:

* `CFBundleIdentifier` - usually it's the same as the `DocSetPlatformFamily`. Not interesting.
* `isDashDocset` - whether or not it's a Dash-style docset (i.e. simpler docSet.dsidx).
* `DocSetPlatformFamily` - Dash uses this as the initial docset keyword, also sometimes for TOC support.
* `DashDocSetFamily` - used to identify different classes of docsets, mostly for TOC support.
* `DashDocSetNameShorteningFamily` - used to shorten names for docsets that use FQN entries. I don't think Zeal does this at all so should not be interesting.
* `DashDocSetDeclaredInStyle` - used to determine how to find out what I call the "declared in". This is what is shown when the user presses Enter when a result is selected. The goal is to show something like the package where a class is declared, or the class where a method is declared and so on. Zeal doesn't have this as far as I know so should not be interesting.
* `isJavaScriptEnabled`
* `DashDocSetBlocksOnlineResources` - if this is set to YES, then Dash doesn't allow the docset to load any online resources, only local stuff
* `dashIndexFilePath`
* `DashDocSetPluginKeyword` - used just to add something extra to match against for the `dash-plugin` keywords. This kind of allows docset-makers to piggyback on an existing keyword that is sent by plugins, instead of relying on plugin makers to update their list of keywords.
* `DashDocSetKeyword` - if this is set, Dash uses it as the initial keyword instead of `DocSetPlatformFamily`
* `DashWebSearchKeyword` - the keyword Dash uses for Google/Stack Overflow searches for the docset.
* `DocSetPlatformVersion` or `CFBundleVersion` - not used for anything
* `CFBundleName`

**Comment by trollixx** [comment]
@Kapeli thank you for the detailed answer!

Zeal really does some things wrong, and doesn't handle others...

**Comment by Kapeli** [comment]
> Zeal really does some things wrong, and doesn't handle others...

That's mostly my fault for not having better documentation and consistency when it comes to docsets. Sorry! 

In the future whenever you want to work on a feature where you want to match the behaviour of Dash, feel free to contact me and I'll try to help and warn you of all the edge cases and so on.

**Comment by trollixx** [comment]
I've implemented a keyword matching logic according to Bogdan's comment. Please, check out the source from 0.1 branch, test, and provide your feedback.
