### ISSUE TITLE
default zoom level in options

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [zealdocs/zeal#424]
This might seem like a silly feature request, but on my system, zeal starts out looking like this: 

![tinyfont-o-vision!](http://i.imgur.com/guXHHH7.png)

This is because I have a 4K monitor, my system is set at 192 DPI, but many programs don't respect that. Ideally zeal would somehow respect those DPI settings, but I can of course just zoom in, as well. The problem is that it resets the zoom level every time zeal restarts. So a default would be nice, or to remember the old settings, or to default to the current DPI (I don't know how you can actually query that BTW, This command works I guess: `xdpyinfo | grep dots`)

**Comment by trollixx** [comment]
You can set the minimum font size in settings, and that should work the same way.

An ability to play nicely with HiDPI screens is something that needs to be implemented. The upcoming switch to Qt WebEngine potentially can solve the issue, but I don't know that for sure. Follow #111 for progress updates.

I am closing this as a duplicate, because the issue comes from the lack of HiDPI support.
