### ISSUE TITLE
socket operation timeout when downloading

### ISSUE THREAD

**Issue by str50** [zealdocs/zeal#446]
Under Arch Linux using 0.21 from zeal-git

What am I missing?

**Comment by alexanderpyoung** [comment]
I'm having the same issue, and I think it's to do with the Zeal /d/com.kapeli/%1/latest redirect hosted on the Zeal website. All queries to this return a URL containing 'london3.kapeli.com' as the host to download the file from (for me - I assume this is generated dynamically based on the location of the requester?). This is inaccessible from a browser, while its DNS resolves. Manually downloading the files from the Dash website has been the workaround I've used in the interim.

I don't think this is anything that can be fixed locally, rather than hardcoding Dash docset servers into Zeal, which is something that has already been decided against, it appears.

**Comment by Kapeli** [comment]
For what it's worth: `london3.kapeli.com` hasn't been around for quite a while now (at least a month I think), as I've replaced it with `frankfurt2.kapeli.com`. Furthermore, I've reorganised my servers yesterday once more and removed a bunch of them.

These servers were removed yesterday:
```
london2.kapeli.com
frankfurt2.kapeli.com
newyork2.kapeli.com
sanfrancisco2.kapeli.com
tokyo2.kapeli.com
```

How does Zeal determine which servers to use?

Dash does it by having 3 hardcoded mirrors: `london.kapeli.com`, `newyork.kapeli.com`, `sanfrancisco.kapeli.com`. It uses those mirrors to load `/feeds/latencyTest_v2.txt` which includes any extra mirrors that might be in use.

**Comment by trollixx** [comment]
Zeal doesn't keep a list of download servers. It just hits go.zealdocs.org,
and then follows redirects. The server tries to choose the closest server.

I'll update the redirect server to scan that file instead of using the
current hard-coded list.

**Comment by trollixx** [comment]
I have updated the mirror list to the following:

```json
    "servers": [
      "frankfurt.kapeli.com",
      "london.kapeli.com",
      "newyork.kapeli.com",
      "sanfrancisco.kapeli.com",
      "sydney.kapeli.com",
      "singapore.kapeli.com",
      "tokyo.kapeli.com"
    ]
```

Should work for now, and I'll make the server refresh the list from `/feeds/latencyTest_v2.txt` later.
