### ISSUE TITLE
Broken css in NodeJS docset

### ISSUE THREAD

**Issue by ketus** [zealdocs/zeal#488]
I use Linux Mint 17.3 x64 with dark theme, and when I use Node.js or Mongoose docSet in Zeal it looks like this:
![image](https://cloud.githubusercontent.com/assets/9350920/12958481/3fd330dc-d032-11e5-8431-86151ec833be.png)

**Comment by trollixx** [comment]
Thanks for reporting! Interesting, I am not quite sure why DE theme affects the webview.

**Comment by ketus** [comment]
@trollixx Maybe there is a way to override this in ZEAL files. Do you know such a way? :)

**Comment by trollixx** [comment]
Currently it's possible to use a user defined CSS file (see
src/resources/browser/highlight.css). You could try adding some overrides
there, and rebuilding Zeal.

Unfortunately, it won't be supported once we switch to Qt WebEngine. But
maybe there's no such issue there.

**Comment by trollixx** [comment]
This is not a real bug in Zeal. Web View just tries to follow the system's defaults when background colour is not set on a web page.

The fresh NodeJS docset doesn't have such problem, but all three OpenGL docsets do. The upcoming release will allow to force a custom user CSS file, and the following snippet fixes the issue.

```css
body {
    background-color: #ffffff;
}
```

I want to keep amount of the CSS code automatically inserted by Zeal to bare minimum, so I think the right way would be to fix the docsets.

@Kapeli could force a white background in OpenGL docsets next time you regenerate them? I guess the problem does not exist on macOS, since the OS has no dark UI theme.

**Comment by Kapeli** [comment]
I've made a note and whenever I'll generate the docsets next I'll add it.
