### ISSUE TITLE
Need feature that press Esc to hide Zeal window

### ISSUE THREAD

**Issue by perqin** [zealdocs/zeal#506]
When I am coding and I press hot key the Zeal window popup up, but I have to close it using my mouse. Could you please allow to set hot key for hiding Zeal window?

**Comment by trollixx** [comment]
Currently you can use the same global shortcut to hide Zeal too. Esc
focuses the query text field atm, I am not sure if this should be changed
or not.

**Comment by ssokolow** [comment]
Why not use `Ctrl+L` to focus the query field since it's Zeal's analogue to a browser/file manager address bar?

...or at least add it as a second option. The current state of thing is actually a bit counter-productive since my muscle memory is programmed to hit Ctrl+L when I want to Google for documentation.

**Comment by trollixx** [comment]
This issue is actually a duplicate of #153.
