### ISSUE TITLE
javascript documentation not working

### ISSUE THREAD

**Issue by ubilli** [zealdocs/zeal#60]
i love zeal app for its offline documentation and its likeness
please i have been trying to get documentation for javascript and some documentations after install when i click on the documentation it would not open....

please i made a tutorial on how to use zeal tuts on this link....... http://www.youtube.com/watch?v=dUx7ExOQvjI

**Comment by trollixx** [comment]
It looks like JavaScript docset has issues with link paths. I've discovered, that all links to files in `JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects` directory (for example, `Infinity` link from index page) are incorrect, because the actual directory name is `Global_objects`. I am not sure how Zeal should handle that.

@Kapeli, how does Dash deal with case sensitivity in file paths? Mac OS X is not case insensitive too.

**Comment by Kapeli** [comment]
> @Kapeli, how does Dash deal with case sensitivity in file paths? Mac OS X is not case insensitive too.

It doesn't deal with it. I was not aware of the broken links. I'm going to regenerate the JavaScript docset. If you notice anything else that is wrong (besides the links to Global_Objects), let me know.

**Comment by trollixx** [comment]
It looks like that was docset generation problem, and Zeal has nothing to do about it.

**Comment by Kapeli** [comment]
The fixed docset is now live. Let me know if you notice anything else that is wrong.
