### ISSUE TITLE
Unable to search terms with '_' char in name

### ISSUE THREAD

**Issue by marmolak** [zealdocs/zeal#650]
Hi. I upgraded to 003bb31a2d9fa3023d7aa2a77fe6fb2e7cfb5f6b and I'm no longer able to search terms which contains '_' char in name.

For example: I'm searching for term wp_post but it found nothing. When I'm searching for wppost it finds wp_post.

Not sure if bug or feature :).

**Comment by trollixx** [comment]
@jkozera ideas? :)

**Comment by jkozera** [comment]
Indeed, that sounds like [my fuzzy search](https://github.com/zealdocs/zeal/commit/e7f631d2d5c55056961bdcb9adfcb1232b7d9862#diff-fa71bce0dbfeb51e61eece48722a4025R760), which replaces '_' in keywords with ' ', so perhaps we should do the same with search queries.

**Comment by trollixx** [comment]
*Some notes for future reference.*

Two problems here. The first one is [how we sanitize](https://github.com/zealdocs/zeal/blob/e7f631d2d5c55056961bdcb9adfcb1232b7d9862/src/libs/registry/docset.cpp#L253) user input for SQL. From [SQLite docs](https://www.sqlite.org/lang_expr.html):

> A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL.

So, it doesn't make any sense to escape `_`, `%` and `\` with back slashes. And specifically escaping underscores messes up our matching and scoring logic.

The second issue has been pointed out by @jkozera above. Right now searching for anything containing a separator (e.g. `std::find`) returns nothing. So, the scope of this bug is a bit broader than only underscores.

A fix is almost ready.

**Comment by FichteFoll** [comment]
Thanks for the fix, working great 👍

**Comment by FichteFoll** [comment]
As mentioned earlier, this generally works.

![2016-12-30_20-51-12_zeal](https://cloud.githubusercontent.com/assets/931051/21571701/103df588-ced2-11e6-8a2b-791e428f2542.png)

However, I'm unable to find `argparse.ArgumentParser.add_argument` in a few situations. I'm using the build from `zeal-unstable-0.3.1-23-g8de33d1-windows-x86.zip`.

Examples:

![2016-12-30_20-52-32_zeal](https://cloud.githubusercontent.com/assets/931051/21571704/103f1a9e-ced2-11e6-8c73-8a888e37fc4f.png)
![2016-12-30_20-51-51_zeal](https://cloud.githubusercontent.com/assets/931051/21571703/103e779c-ced2-11e6-9253-801e39177677.png)
![2016-12-30_20-51-19](https://cloud.githubusercontent.com/assets/931051/21571702/103e5992-ced2-11e6-8eab-b0327d447107.png)

As you can see from the "argparse" query, this entry does exist.

**Comment by marmolak** [comment]
Cool. Thank you. Works for me :). (Running under macOS).
