### ISSUE TITLE
There is no ios(objective-c) docsets?

### ISSUE THREAD

**Issue by 1987skywalker** [zealdocs/zeal#680]
I can't find it in zeal. Can I download it and add it to zeal manually?
https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex

**Comment by OKNoah** [comment]
I was going to say it might be because Apple distributes their documentation right in the OS help files, but looks like you do have some kind of link to them. Dash also asked you to install Xcode and install the docs on the system to get the docs in the app (it just looked in the system folders for them rather than download again).

**Comment by trollixx** [comment]
We neither support any Apple's docsets, and nor running on macOS. No changes about in the observable future.

**Comment by RJVB** [comment]
Zeal runs just fine on OS X (dunno about macOS, aka 10.12+ O:-) )

https://github.com/RJVB/macstrop/tree/master/devel/zeal

**Comment by trollixx** [comment]
@RJVB And looks super ugly :)

Anyway, while supporting different documentation formats is interesting, I doubt we'd ever get into Apple's proprietary stuff. There are just too many other things to do.

I'll leave this issue open for a bit, just a reminder for myself to create a wiki page on different formats.

**Comment by RJVB** [comment]
@trollix: super ugly? When code uses only Qt's standard choices for font and widget sizes the result will never look good anywhere, but will always remain some kind of lowest common denominator. This is worse on Mac than elsewhere because you end up with the huge default system font in more places than you should, but the Macintosh widget style also uses too much spacing.
I don't mind, I have KF5 installed properly and use a personal QtCurve theme. With that Qt applications look as good on Linux as they do on Mac O:-)

**Comment by RJVB** [comment]
Re: the Apple docs. Do you have access to the sqlite3 index or is that off-limit too? Because if it isn't, it might be possible to fetch the html documentation from the website, and rebuild a standard .docset from the index.

**Comment by tomaspinho** [comment]
I've spent 2 evenings (not a C/C++/QT dev) trying to build Zeal on macOS (Sierra, 10.12), and managed to do it. I updated the instructions for homebrew on the relevant pages in the wiki.

I was just wondering if choosing to not support OSX is out of respect for Kapeli, due to the explicit usage of their docsets, or if it is for some other reason, technical or otherwise (OS fanboyism).

**Comment by trollixx** [comment]
@tomaspinho Please see #24.

**Comment by tomaspinho** [comment]
@trollixx thanks 👍 . What about users like me and @RJVB who may be maintaining or publishing their build scripts?

**Comment by trollixx** [comment]
Keep them to yourself :) I think we are fine as long as Zeal stays out of popular software sources like Homebrew.

**Comment by trollixx** [comment]
Copied link to the [wiki](https://github.com/zealdocs/zeal/wiki/Xcode-Feed-Format).

**Comment by RJVB** [comment]
Because the question came up once more (for me): Objective-C is not an exclusive-to-Apple language. In other words, having a docset for it (just as there's a docset for C and for C++) shouldn't be a problem at all and it should thus be perfectly legitimate to ask for (or provide) such a docset.

**Comment by trollixx** [comment]
@RJVB IIRC on macOS Dash shows docs from XCode, and not it's own docsets.
