### ISSUE TITLE
Why remove support for Qt WebEngine?

### ISSUE THREAD

**Issue by Jackson-soft** [zealdocs/zeal#692]
Qt5.8 build failed

**Comment by trollixx** [comment]
Mostly because of the way it was implemented. Ugly hacks all around, and it also lacked feature parity with the Qt WebKit integration. Also with Qt WebKit [coming back](https://qtwebkit.blogspot.com/2016/08/qtwebkit-im-back.html), it just doesn't make much sense to keep both engines around. Qt WebKit provides deep integration with Qt, better performance and smaller memory footprint.

On a side note, with proper abstraction and encapsulation in a single plugin, I am ready to add it back, assuming someone else wants to maintain that.

**Comment by Jackson-soft** [comment]
but Qt WebEngine is the future of Qt

**Comment by trollixx** [comment]
Qt WebEngine has other use cases, but a lightweight web view is not one of them.

**Comment by ferronrsmith** [comment]
Same issue, can't get this to build on `5.7.1`.

**Comment by trollixx** [comment]
@ferronrsmith Please use [qt-webkit-ng](https://github.com/annulen/webkit). There are prebuilt binaries for Windows, and some Linux distros already provide it as well.

**Comment by e-cloud** [comment]
@trollixx you may add more development info about installing qt-webkit with qt version >= 5.6  to `ReadMe.md`.
