### ISSUE TITLE
Corrupted docset list

### ISSUE THREAD

**Issue by MichaelSolotky** [zealdocs/zeal#713]
Hi, I've just installed zeal on my fedora 25 (sudo dnf install zeal). I'm trying to open docsets (panel Tools -> docsets...) and it writes me "Corrupted docset list: illegal value". 
![screenshot_20170402_112525](https://cloud.githubusercontent.com/assets/25284863/24585608/cfff8f68-1797-11e7-82e5-25cf9e2e7569.png)

When I click "Available" there are no docsets.
![screenshot_20170402_113255](https://cloud.githubusercontent.com/assets/25284863/24585633/317ea01c-1798-11e7-84b8-2de2accfed6f.png)

Then I try to open the page zealdocs.org from zeal and this note appears
![screenshot_20170402_113627](https://cloud.githubusercontent.com/assets/25284863/24585672/c6a7c7fe-1798-11e7-9d3d-54c00b9049f4.png)

Also I'm running zeal from terminal and when I close zeal window it's still running.
It's a message from termial:
QXcbConnection: XCB error: 3 (BadWindow), sequence: 4214, resource id: 39853580, major code: 40 (TranslateCoords), minor code: 0
Then I stop the process with ^C and try to open it one more time and it says:
"Another application instance can be still running, or has crashed.
Make sure to start Zeal only once."
Please fix that things)

**Comment by trollixx** [comment]
_Please report only one problem per ticket in the future, doing otherwise leads to a mess, and makes it hard to track._

The first one isn't a bug, but rather an error message that the downloaded content cannot be parsed. I guess I should make the error message more clear, and give a retry option. Clicking `Refresh` will also lead to an attempt to re-download the docset index. Your issue can be caused by something preventing Zeal from reaching our [API backend](http://api.zealdocs.org/v1/docsets). So, please check your connection, firewall settings, etc, if the problem does not vanish on its own.

The `KIOExec` error is not generated by Zeal. We only rely on the system to open an external URL, no custom logic there.

The XCB error [appears](https://bugs.kde.org/show_bug.cgi?id=340318#c2) to be KDE specific and safe to ignore.

The last warning was originally intentional, but I believe it just causes more confusion than helps. I am planning to improve our single-app logic, so there would be no need to ask user for confirmation.

**Comment by trollixx** [comment]
The first has been already reported as #566.

**Comment by trollixx** [comment]
As I've said in https://github.com/zealdocs/zeal/issues/713#issuecomment-291035033 there's not much we can do here, other than improve the user experience a bit, and try to download the docset index again.
