### ISSUE TITLE
Windows binaries are now 64-bit

### ISSUE THREAD

**Issue by Nils85** [zealdocs/zeal#785]
But why only 64-bit ??
MSVC 2015 can't compile in 32-bit?

**Comment by trollixx** [comment]
I guess because it's 2017, and I don't have any desire to build all our dependencies (especially Qt WebKit) for two architectures.

You can always build Zeal yourself, if the official build doesn't work for you. If you or someone else wishes to maintain 32-bit builds, I'll try to offer my assistance.

**Comment by Nils85** [comment]
I understand, but why not propose only the 32-bit version in this case?
Zeal really needs the 64-bit technology to run normally?

What is the advantage of choosing 64-bit rather than 32-bit?
Or is there a technical disadvantage with the 32-bit version?

**Comment by trollixx** [comment]
The ugly `Program Files (x86)` on 64-bit Windows is the main reason of not having 32-bit version.

On a more serious note, I think at the moment difference is not noticeable. In theory SQLite and WebKit should perform a bit better, but without benchmarks it's impossible to say for sure.

Regardless of that, it's been over 10 years since Intel introduced the last 32-bit only CPU. Linux distributions are already dropping 32-bit support, eventually Microsoft will do the same.

Right now Zeal should build and work just fine on 32-bit, so if there is a serious demand, we can discuss whether it would be a good idea to support old hardware.

**Comment by Nils85** [comment]
Ok ok... Anyway, thanks for your answer!
I don't know if I could help you to publish 32-bit versions for new releases because I don't have good knowledge in C++. (I am C# and PHP developer)

But it would be cool if you left the link to installation package of version 0.3.1 for "old" hardware in the download page  :)
Temporarily, because right now I have to search on strange sites like this one to find it :
[https://www.techworld.com/download/developer-programming/zeal-031-3330988/](https://www.techworld.com/download/developer-programming/zeal-031-3330988/)

**Comment by trollixx** [comment]
You can find all previous versions [here](https://bintray.com/zealdocs/windows/zeal).

**Comment by Abu3safeer** [comment]
Thank you, I wish 0.3.1 still working.

**Comment by trollixx** [comment]
@Abu3safeer 0.5.0 will have builds for 32-bit Windows.

**Comment by trollixx** [comment]
FYI: Due to demand 32-bit builds for Windows have been reinstated for v0.5.0.

**Comment by trollixx** [comment]
And v0.5.0 is now officially out, grab 32-bit builds for your good old hardware :)
