### ISSUE TITLE
Feature request: premium version

### ISSUE THREAD

**Issue by latortuga** [zealdocs/zeal#924]
Several other issues have been opened and closed about the ads issue so I won't beat a dead horse too hard. Advertisements don't respect your users' privacy - today Carbon Ads is an ethical ad network, tomorrow it could be sold to the highest bidder.

Please consider accepting money from your actual customers rather than ad networks. Your market is developers and I know they'd would be happy to pay you for your work. As a business owner, I happily OK and pay for any and all software requests by any of my developers.

**Comment by trollixx** [comment]
Let me first clarify that the ads in Zeal are not meant to make any real money. At some point Carbon folks reached out to me, and I just said why not. It's kind of fun to see something dripping into my PayPal account each month, but frankly I don't use the funds for anything aside from paying some tiny maintenance costs.

If you are concerned about privacy, feel free to disable the ads in the settings. Some Linux distributions do that by default.

I've been considering ways to make some real profits from Zeal, but have never done anything to make that happen. I am more inclined towards providing some enterprise solutions, while keeping Zeal itself free and open source. With the current state of Zeal, I really don't see how would introducing a premium version or a subscription plan worth it.

Also, I do have a full-time job, so Zeal gets very little of my attention. Sometimes weeks pass between commits, or me simply addressing an issue ticket. I am not sure it would be fair to charge any money in such situation, or even collect donations.

**Comment by trollixx** [comment]
It's kind of a chicken and egg problem. To make Zeal profitable, I'd need to spend more time on it, but for that I'd need to make it profitable first :)

Frankly, I really don't want Zeal to be a paid or a closed source app. So, I am reluctantly looking into other ways to monetize it. And, no not with ads.

In the meanwhile I'll keep this ticket open as a reference for the similar questions I get every now and then. And everyone is welcome to express their opinion.

**Comment by SirCmpwn** [comment]
Throw up a Patreon and Liberapay page and I'd throw in some dough. If you just need to meet recurring costs it can be a good approach.

**Comment by vpiotr** [comment]
I'd pay for Zeal to keep it on the surface. Maybe not 100's of US dollars, but a small fee per year (for updates).

**Comment by Patabugen** [comment]
+1 for at least a Patreon or donations page - Zeal is one of those apps I'd really miss if it were no longer around. It helps me make money every day, and I'd like to be able to feed some of that back to the person who make my life easier.

**Comment by trollixx** [comment]
Okay, for those who asked, here's the link: https://www.buymeacoffee.com/trollixx

Patreon required too much typing, while Buy Me A Coffee was a click-through experience, and setting up a Stripe account was quite interesting.

P.S. In some other ticket I already mentioned that eventually I'll remove the ads, but for now, if you are concerned about privacy or they simply bother you, just disable them in settings.

**Comment by ddevault** [comment]
Thanks for setting up a donation sink! However, until the ads are removed, I'll abstain.

**Comment by Patabugen** [comment]
Superb - thanks @trollixx ! (and also thanks for the simple tick box so anyone can remove ads - I appreciate the simplicity, though can see that some people might want to be able to block them before even the first one loads)

**Comment by trollixx** [comment]
@latortuga editing readme is too much work, but will do eventually! And thanks for the coffee! :)

#779 is tracking removal of the ads.

**Comment by JKJameson** [comment]
Please add an ad-free option. Having an advert in your face and having to scroll down every section of a document is irritating.
At the very least move the ad so that it floats at the top right or something that doesn't limit the content visible on the screen.
https://imgur.com/a/Gde0pHB

**Comment by trollixx** [comment]
@JKJameson the ad has been removed in the master, there are some issues with releasing a new version though.

**Comment by FalcoGer** [comment]
this is open source. as soon as you add advertisements I'll fork it and throw them out. There is nothing to be gained here. Ads don't have a place in free and open source projects. If you want to support the devs then add a donate button in the about section or whatever.

**Comment by JKJameson** [comment]
@FalcoGer lol you have nothing to gain with that attitude. Go suck a lemon.

**Comment by trollixx** [comment]
@FalcoGer Or you can just read the thread, and see that the ads can be easily disabled, and were removed in 680a1baa701581fdf5fcd92e3c2510e136666d3f. So for a completely ad-free version you can use CI builds, build it yourself, or wait for the next official release.

To be pedantic ads have nothing to do with the license. GPL doesn't say anything on the matter.

Forking an open source is totally fine, that's the whole point of releasing something under a license permitting that. Using Zeal's backend services or docsets would be another question, as neither are open source.

Anyway, this issue is about a premium version of Zeal, which does not exist, and unlikely to happen in the near term.

If Zeal existed for macOS, I would have released it to the App Store as a paid app, but that's not the case. Plus it would have required re-licensing under a more permissive license.

Probably, another alternative would be Microsoft Store, but last I checked that was also currently not an option due to various limitations.

The best scenario would be providing some extra value to enterprise customers, while keeping the app completely open source, but again I do not have much time to invest into developing such features.

On this note I think this ticket can be closed.

**Comment by trollixx** [comment]
Let's all be civil here please. @JKJameson I edited your comment a bit.
